server:
  port: 8082
spring:
  thymeleaf:
    cache: false
    prefix: file:src/main/resources/templates/
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring2502_heathyfood_test?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul&useSSL=false
    username: root
    password:
  mail:
    host: smtp.gmail.com
    port: 587
    username: hellohealthy1125@gmail.com
    password: dmqy mzdt kjyk imte
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  springdoc:
    api-docs:
      enabled: true
    swagger-ui:
      path: /swagger-ui/index.html
      groups-order: DESC
      doc-expansion: none
      tags-sorter: alpha
      operationsSorter: method
      display-request-duration: true

public:
  api:
    key: pI6lmSyDsoqg3DxlrZuoNa8%2B39ZrVXXrNoxlFSaqKSFGjqLT9h8fSSXls98F30rg7ImwzJuH%2BmMvL%2FcAVzDDiA%3D%3D


mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.healthFood.lab.spring2502_heathFood.vo

custom:
  type-aliases-package: com.healthFood.lab.spring2502_heathFood.vo
  siteName: 헬스 푸드 랩(HealthyFoodLab)
  siteMainUri: http://localhost:8088
  emailFrom: HealthyFoodLab Support Team
  emailFromName: HealthyFoodLab
